# Groups

# Manila - Share
- id: manila-share
  type: group
  role: [manila-share]
  tasks: [hiera, globals, setup_repositories, tools, logging, netconfig, firewall, hosts, ntp-client, dns-client, cgroups, deploy_start, openstack-network-common-config, openstack-network-plugins-l2]
  required_for: [deploy_end]
  requires: [deploy_start, primary-controller]
  parameters:
    strategy:
      type: one_by_one

# Manila - Data

- id: manila-data
  type: group
  role: [manila-data]
  tasks: [hiera, globals, setup_repositories, tools, logging, netconfig, firewall, hosts, ntp-client, dns-client, cgroups, deploy_start]
  required_for: [deploy_end]
  requires: [deploy_start, primary-controller]
  parameters:
    strategy:
      type: one_by_one

# Tasks

- id: manila-generate_keys
  type: shell
  groups: [master]
  version: 2.1.0
  requires: [pre_deployment_start]
  required_for: [manila-copy_keys]
  parameters:
    cmd: sh /etc/puppet/modules/osnailyfacter/modular/astute/generate_keys.sh -p /var/lib/fuel/keys/ -i {CLUSTER_ID} -s 'manila'
    timeout: 180

- id: manila-copy_keys
  type: copy_files
  version: 2.1.0
  role: ['/.*/']
  required_for: [pre_deployment_end]
  requires: [manila-generate_keys]
  cross-depends:
      - name: manila-generate_keys
        role: master
  parameters:
    files:
      - src: /var/lib/fuel/keys/{CLUSTER_ID}/manila/manila.pub
        dst: /var/lib/astute/manila/manila.pub
      - src: /var/lib/fuel/keys/{CLUSTER_ID}/manila/manila
        dst: /var/lib/astute/manila/manila
    permissions: '0600'
    dir_permissions: '0700'

- id: manila-gen_password
  type: shell
  groups: [master]
  version: 2.1.0
  requires: [pre_deployment_start]
  required_for: [manila-hiera]
  parameters:
    cmd: sh /var/www/nailgun/plugins/fuel-plugin-manila-1.0/gen_password.sh {CLUSTER_ID}
    timeout: 180

- id: manila-hiera
  type: copy_files
  version: 2.1.0
  role: ['/.*/']
  required_for: [manila-keystone]
  requires: [manila-gen_password]
  cross_depends:
    - name: manila-gen_password
      role: master
  parameters:
    files:
      - src: /etc/fuel/cluster/{CLUSTER_ID}/fuel-plugin-manila.yaml
        dst: /etc/hiera/plugins/fuel-plugin-manila.yaml
    permissions: '0600'
    dir_permissions: '0700'

- id: manila-keystone
  type: puppet
  groups: [primary-controller]
  version: 2.1.0
  requires: [manila-hiera, primary-openstack-controller]
  required_for: [manila-db]
  cross-depends:
    - name: keystone-db
  cross-depended-by:
    - name: deploy_end
  parameters:
    puppet_manifest: "puppet/manifests/keystone.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600

- id: manila-db
  type: puppet
  groups: [primary-controller]
  version: 2.1.0
  required_for: [manila-main]
  requires: [primary-database, database, manila-hiera]
  condition:
    yaql_exp: >
      changedAny($.mysql, $.network_metadata.vips, $.get('database_vip'))
  cross-depends:
    - name: /^(primary-)?database$/
  cross-depended-by:
    - name: deploy_end
  parameters:
    puppet_manifest: "puppet/manifests/db.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600

- id: manila-install-controller
  type: puppet
  groups: [primary-controller, controller]
  version: 2.1.0
  required_for: [manila-main]
  requires: [manila-db]
  cross-depends:
     - name: manila-db
  parameters:
    puppet_manifest: "puppet/manifests/install.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600

- id: manila-share-network-common-config
  type: puppet
  version: 2.1.0
  groups: [manila-share]
  required_for: [openstack-network-end]
  requires: [hosts, firewall]
  condition:
    yaql_exp: >
      changedAny($.get('openstack_network'), $.get('verbose'), $.debug,
      $.quantum_settings, $.neutron_advanced_configuration, $.rabbit,
      $.ceilometer, $.network_scheme, $.get('use_syslog'),
      $.get('use_stderr'), $.get('syslog_log_facility_neutron'),
      $.network_metadata.nodes.values().where(
        $.node_roles.any($.matches('controller'))).network_roles.select(
          $.get('mgmt/messaging')),
      $.get('amqp_hosts'), $.get('kombu_compression'))
  cross-depends:
    - name: /^openstack-network-common-config$/
      role: primary-controller
  parameters:
    puppet_manifest: /etc/puppet/modules/openstack_tasks/examples/openstack-network/common-config.pp
    puppet_modules: /etc/puppet/modules
    timeout: 1800


- id: manila-share-network-plugins-l2
  type: puppet
  version: 2.1.0
  groups: [manila-share]
  required_for: [manila-install-share-data]
  requires: [manila-share-network-common-config]
  refresh_on: [neutron_agent_ovs]
  cross-depends:
    - name: primary-openstack-network-plugins-l2
      role: primary-controller
  parameters:
    puppet_manifest: /etc/puppet/modules/openstack_tasks/examples/openstack-network/plugins/ml2.pp
    puppet_modules: /etc/puppet/modules
    timeout: 1800


- id: manila-install-share-data
  type: puppet
  groups: [manila-share, manila-data]
  version: 2.1.0
  required_for: [deploy_end]
  requires: [hosts]
  parameters:
    puppet_manifest: "puppet/manifests/install_sd.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600

- id: manila-init-controller
  type: puppet
  groups: [primary-controller, controller]
  version: 2.1.0
  required_for: [manila-main]
  requires: [manila-install-controller]
  parameters:
    puppet_manifest: "puppet/manifests/init_controller.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600

- id: manila-init-share
  type: puppet
  groups: [manila-share]
  version: 2.1.0
  required_for: [deploy_end]
  requires: [manila-install-share-data]
  parameters:
    puppet_manifest: "puppet/manifests/init_share.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600

- id: manila-init-data
  type: puppet
  groups: [manila-data]
  version: 2.1.0
  required_for: [deploy_end]
  requires: [manila-install-share-data]
  parameters:
    puppet_manifest: "puppet/manifests/init_data.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600


- id: manila-image_upload
  type: puppet
  groups: [primary-controller]
  version: 2.1.0
  required_for: [manila-main]
  requires: [manila-install-controller]
  parameters:
    puppet_manifest: "puppet/manifests/image_upload.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600

- id: manila-haproxy
  type: puppet
  groups: [primary-controller, controller]
  version: 2.1.0
  requires: [manila-install-controller]
  parameters:
    puppet_manifest: "puppet/manifests/haproxy.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600

- id: manila-main
  type: puppet
  groups: [primary-controller, controller]
  version: 2.1.0
  cross-depends:
    - name: manila-db
  cross-depended-by:
    - name: deploy_end
  requires: [manila-install-controller, manila-haproxy]
  parameters:
    puppet_manifest: "puppet/manifests/site.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600

- id: manila-main_share
  type: puppet
  groups: [manila-share]
  version: 2.1.0
  cross-depends:
    - name: manila-main
  required_for: [deploy_end]
  requires: [manila-init-share]
  parameters:
    puppet_manifest: "puppet/manifests/site_share.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600

- id: manila-main_data
  type: puppet
  groups: [manila-data]
  version: 2.1.0
  cross-depends:
    - name: manila-main
  required_for: [deploy_end]
  requires: [manila-init-data]
  parameters:
    puppet_manifest: "puppet/manifests/site_data.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600
