- id: manila-generate_keys
  type: shell
  groups: [master]
  version: 2.1.0
  requires: [pre_deployment_start]
  required_for: [manila-copy_keys]
  parameters:
    cmd: sh /etc/puppet/modules/osnailyfacter/modular/astute/generate_keys.sh -p /var/lib/fuel/keys/ -i {CLUSTER_ID} -s 'manila'
    timeout: 180

- id: manila-copy_keys
  type: copy_files
  version: 2.1.0
  role: ['/.*/']
  required_for: [pre_deployment_end]
  requires: [manila-generate_keys]
  cross-depends:
      - name: manila-generate_keys
        role: master
  parameters:
    files:
      - src: /var/lib/fuel/keys/{CLUSTER_ID}/manila/manila.pub
        dst: /var/lib/astute/manila/manila.pub
      - src: /var/lib/fuel/keys/{CLUSTER_ID}/manila/manila
        dst: /var/lib/astute/manila/manila
    permissions: '0600'
    dir_permissions: '0700'

- id: manila-gen_password
  type: shell
  groups: [master]
  version: 2.1.0
  requires: [pre_deployment_start]
  required_for: [manila-hiera]
  parameters:
    cmd: sh /var/www/nailgun/plugins/fuel-plugin-manila-1.0/gen_password.sh {CLUSTER_ID}
    timeout: 180

- id: manila-hiera
  type: copy_files
  version: 2.1.0
  role: ['/.*/']
  required_for: [manila-keystone]
  requires: [manila-gen_password]
  cross_depends:
    - name: manila-gen_password
      role: master
  parameters:
    files:
      - src: /etc/fuel/cluster/{CLUSTER_ID}/fuel-plugin-manila.yaml
        dst: /etc/hiera/plugins/fuel-plugin-manila.yaml
    permissions: '0600'
    dir_permissions: '0700'

- id: manila-keystone
  type: puppet
  groups: [primary-controller]
  version: 2.1.0
  requires: [manila-hiera, primary-openstack-controller]
  required_for: [manila-db]
  cross-depends:
    - name: keystone-db
  cross-depended-by:
    - name: deploy_end
  parameters:
    puppet_manifest: "puppet/manifests/keystone.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600

- id: manila-db
  type: puppet
  groups: [primary-controller]
  version: 2.1.0
  required_for: [manila-main]
  requires: [primary-database, database, manila-hiera]
  condition:
    yaql_exp: >
      changedAny($.mysql, $.network_metadata.vips, $.get('database_vip'))
  cross-depends:
    - name: /^(primary-)?database$/
  cross-depended-by:
    - name: deploy_end
  parameters:
    puppet_manifest: "puppet/manifests/db.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600

- id: manila-install
  type: puppet
  groups: [primary-controller, controller]
  version: 2.1.0
  required_for: [manila-main]
  requires: [manila-db]
  cross-depends:
     - name: manila-db
  parameters:
    puppet_manifest: "puppet/manifests/install.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600

- id: manila-image_upload
  type: puppet
  groups: [primary-controller]
  version: 2.1.0
  required_for: [manila-main]
  requires: [manila-install]
  parameters:
    puppet_manifest: "puppet/manifests/image_upload.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600

- id: manila-haproxy
  type: puppet
  groups: [primary-controller, controller]
  version: 2.1.0
  requires: [manila-install]
  parameters:
    puppet_manifest: "puppet/manifests/haproxy.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600

- id: manila-main
  type: puppet
  groups: [primary-controller, controller]
  version: 2.1.0
  cross-depends:
    - name: manila-db
  cross-depended-by:
    - name: deploy_end
  requires: [manila-install, manila-haproxy]
  parameters:
    puppet_manifest: "puppet/manifests/site.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600
