- id: manila-start
  type: puppet
  groups: [primary-controller, controller]
  version: 2.1.0
  cross-depends:
    - name: deploy_start
  cross-depended-by:
    - name: deploy_end
  parameters:
    puppet_manifest: "puppet/manifests/notify.pp"
    puppet_modules: "."
    timeout: 3600

- id: manila-hiera
  type: puppet
  groups: [primary-controller, controller]
  version: 2.1.0
  cross-depends:
    - name: manila-start
  cross-depended-by:
    - name: deploy_end
  parameters:
    puppet_manifest: "puppet/manifests/populate_hiera.pp"
    puppet_modules: "."
    timeout: 3600

- id: manila-keystone
  type: puppet
  groups: [primary-controller, controller]
  version: 2.1.0
  cross-depends:
    - name: manila-hiera
  cross-depended-by:
    - name: deploy_end
  parameters:
    puppet_manifest: "puppet/manifests/populate_hiera.pp"
    puppet_modules: "."
    timeout: 3600
    
- id: manila-main
  type: puppet
  groups: [primary-controller, controller]
  version: 2.1.0
  cross-depends:
    - name: manila-kestone
  cross-depended-by:
    - name: deploy_end
  parameters:
    puppet_manifest: "puppet/manifests/install.pp"
    puppet_modules: "."
    timeout: 3600
